version: "3"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: els-compose
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana-compose
    ports:
      - 5601:5601
    volumes:
      - /opt/kibana/kibana-7.6.1-linux-x86_64/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    external_links:
      - els-compose:elasticsearch
    networks:
      - elk_network
    depends_on:
      - es
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logstash-compose
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - /opt/logstash/logstash-7.6.1/config/:/usr/share/logstash/config/ 
    external_links:
      - els-compose:elasticsearch
    networks:
      - elk_network
    depends_on:
      - es
     
networks:
  elk_network:
