version: "3.7"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: els-compose
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana-compose
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    external_links:
      - els-compose:elasticsearch
    networks:
      - elk_network
    depends_on:
      - es
  logstash:
    # image: docker.elastic.co/logstash/logstash:7.6.1
    build:
      context: .
      dockerfile: logstash_dockerfile
    hostname: logstash
    volumes:
      - ./logstash/config/:/usr/share/logstash/config/ 
    container_name: logstash-compose
    environment:
      LS_OPTS: "--config.reload.automatic"
    ports:
      - "5044:5044/tcp"
      - "5044:5044/udp"
      - "9600:9600"
    volumes:
      - ./logstash/config/:/usr/share/logstash/config/ 
    external_links:
      - els-compose:elasticsearch
    networks:
      - elk_network
    depends_on:
      - es
     
networks:
  elk_network:
