  - pipeline.id: mylogs
    path.config: "/usr/share/logstash/config/myconfig.cfg"
    pipeline.workers: 1
    pipeline.batch.size: 125
  - pipeline.id: pipe2
    path.config: "/usr/share/logstash/config/myconfig2.cfg"
    queue.type: persisted
